name: Security Audit

on:
  pull_request:
    branches: [ master, main, develop ]
  push:
    branches: [ master, main, develop ]
  schedule:
    # Run weekly security audit every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security-audit:
    name: Security Vulnerability Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit with high severity
        run: npm audit --audit-level=high
        continue-on-error: true
        id: audit

      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-audit
          path: |
            package-lock.json
          retention-days: 30

      - name: Comment audit results on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const auditExitCode = '${{ steps.audit.outcome }}' === 'failure' ? 1 : 0;
            
            if (auditExitCode !== 0) {
              const issue = `## 🚨 Security Audit Failed
              
              This PR contains high or critical severity vulnerabilities.
              
              Please run \`npm audit --audit-level=high\` locally and fix any issues before merging.
              
              Review the audit report in the workflow artifacts for details.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: issue
              });
            }

      - name: Fail workflow if vulnerabilities found
        if: failure()
        run: |
          echo "⚠️ High or critical severity vulnerabilities detected!"
          echo "Please fix these issues before merging the PR."
          echo "Run 'npm audit' locally to see details."
          exit 1

  snyk-security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk test
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk.sarif
          wait-for-processing: false

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Verify package.json integrity
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "❌ package-lock.json is missing!"
            echo "Run 'npm install' to generate it."
            exit 1
          fi
          
          npm audit --production --audit-level=moderate

